# Generated by Django 4.1.2 on 2022-10-27 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artist',
            new_name='Artiste',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artist_id',
            new_name='artiste_id',
        ),
    ]
