# Generated by Django 4.1.2 on 2022-10-27 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_rename_artist_artiste_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lyrics',
            name='Song',
        ),
        migrations.RemoveField(
            model_name='song',
            name='Artist',
        ),
        migrations.AlterField(
            model_name='lyrics',
            name='song_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musicapp.song'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artiste_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musicapp.artiste'),
        ),
    ]
